name: Checks for A and B

on: [pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        java-version: ["17"]
        dir: ["A", "B"]
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew test
